name: Test run

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Enable Windows Store
      run: Get-AppxPackage -allusers Microsoft.WindowsStore | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}
    - name: Run script
      run: ./windows.ps1
      shell: powershell
